name: Testing

on:
  push:
    branches: [ bleeding ]
  pull_request:
    branches: [ bleeding ]

jobs:
  composer:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      working-directory: library
      
    - name: Get Composer Cache Directory
      id: composer-cache
      working-directory: library
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
      
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: library/vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
      working-directory: library

  phpstan:
   needs: composer
   runs-on: ubuntu-18.04
   
   steps:
    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      working-directory: library
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
      
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: library/vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest
      working-directory: library
            
    - name: phpstan on library
      uses: chindit/actions-phpstan@master
      with:
        arguments: "analyse library/Ivoz --level 4 --ansi --no-progress --autoload-file=library/vendor/autoload.php --configuration=library/phpstan.neon"
